### ISSUE TITLE
Operator Refactoring Checklist

### ISSUE THREAD

**Issue by reyna-abhyankar** [flexflow/FlexFlow#725]
### Operator Refactoring Checklist
- [ ] Define input tensors explicitly in `get_ouptut_shape.h`
- [ ] In `op-attrs` header files, use visitable and hashable instead of operator overloads
- [ ] Implementations for `get_output_shape()` and `is_valid()` in `op-attrs`
	- Assertion checking that was typically done in the constructor should be moved to `is_valid`
- [ ] Add layer in `ComputationGraph`
- [ ] Add task IDs to `tasks.cc`

### Operator Implementation Checklist
- [ ] Slots for each input, output, and gradient tensor, as well as arguments (`ATTRS`, `PROFILING`, `PER_DEVICE_STATE`, `HANDLE`)
- [ ] `get_data_dependencies()` **-- ???**
- [ ] `register_tasks<..._TASK_ID>()` for `INIT`, `FWD`, and `BWD`
	- Create `TaskSignature` and add slots relevant to that task
- [ ] `init(...)`, `forward(...)`, `backward(...)`
	- Returns a `TaskInvocation` that is composed of a `TaskBinding` which binds slots to tensors, arguments and the task ID
- [ ] `init_task`, `forward_task`, `backward_task` should all be `static` and take advantage of `TaskArgumentAccessor` to access relevant tensors and arguments. `forward_task` and `backward_task` call relevant kernel functions while `init_task` should return a `PerDeviceOpState` 
- [ ] `measure_operator_cost()`
	- Now takes a `SimEnvironment`, `[x]Attrs`, and input tensors listed explicitly, along with `ProfilingSettings` and `MachineView`

@lockshaw does this look like an accurate (albeit probably not exhaustive) checklist for each operator?

**Comment by lockshaw** [comment]
@KateUnger Closing this as it's not really a TODO, but feel free to refer back to it :slightly_smiling_face:
